### ISSUE TITLE
element_path 获取不到

### ISSUE THREAD

**Issue by sunsetroads** [Mao-x-w/FlutterAopDemo#6]
dependency_overrides:
  kernel:
    path: /Users/wenxuemao/custom/flutter/xianyuDartSdk/sdk/pkg/kernel
    
这个库下载下来后里面的代码需要改哪些呢？我这的 element_path 获取不到

**Comment by Mao-x-w** [comment]
代码不用动，改到对应的分支上就可以

**Comment by sunsetroads** [comment]
bool _shouldAddToPath(Element element)  这个方法都会返回 false 导致element_path 都没有拼上，我看你的博客 https://juejin.cn/post/6976811419677392903 定位一个 widget 是否是自己的，需要对 sdk/pkg/kernel 里的 track_widget_constructor_locations 进行更改，是只需要改这些吗？我改完还是不生效
// 判断当导入类中有我们定义的类的时候
if (importUri.path.contains('hook_impl.dart')) {
    for (Class class_ in library.classes) {
        // 获取到所有的类，如果有_CustomHasCreationLocation，那么把_hasCreationLocationClass赋值为_CustomHasCreationLocation，下面同理
      if (class_.name == '_CustomHasCreationLocation') {
        _hasCreationLocationClass = class_;
      } else if (class_.name == '_CustomLocation') {
        _locationClass = class_;
      }
    }
  }

**Comment by Mao-x-w** [comment]
我代码中已加[track_widget_custom_location.dart](https://github.com/Mao-x-w/FlutterAopDemo/blob/dev/lib/src/transformer/aop/track_widget_custom_location.dart)

**Comment by Mao-x-w** [comment]
close

**Comment by sunsetroads** [comment]
请问下，如何适配 flutter sdk 其他版本呢？怎么搭建这个 [track_widget_custom_location.dart](https://github.com/Mao-x-w/FlutterAopDemo/blob/dev/lib/src/transformer/aop/track_widget_custom_location.dart)的开发调试环境可以指导下吗？我 把主工程拉下来 pub get 后依然很多报错
